### ISSUE TITLE
Disable Build version check if not required

### ISSUE THREAD

**Issue by elbidone** [meumobi/infomobi#141]
Following App DesenvolveSP don't use and it raises the following error

```
[phonegap] [console.log] [API:errorInterceptor]: BEGIN
[phonegap] 200 /socket.io/?EIO=2&transport=polling&t=1449600197564-13&sid=uOYChpZ04pV5-PMVAAAB
[phonegap] [console.log] { status: 404,
  config: 
   { method: 'JSONP',
     transformRequest: [ null ],
     transformResponse: [ null ],
     url: 'https://build.phonegap.com/api/v1/apps/?auth_token=&callback=JSON_CALLBACK',
     headers: 
      { Accept: 'application/json, text/plain, */*',
        'X-Visitor-Token': 'c200c8e595fef7ded1ae3534f424c6a8713e2cd9' } },
  statusText: 'error' }
[phonegap] [console.log] [API:errorInterceptor]: END
[phonegap] [console.error] TypeError: Cannot read property 'error' of undefined
[phonegap]     at error (file:///data/data/com.adobe.phonegap.app/files/files/phonegapdevapp/www/js/app.min.js:42499:68)
[phonegap]     at file:///data/data/com.adobe.phonegap.app/files/files/phonegapdevapp/www/js/app.min.js:10259:13
```

**Comment by elbidone** [comment]
remove $rootScope.versionServiceIsEnabled. Should refactor it if we want to reuse
