### ISSUE TITLE
'MissingControllerException' raised when call /forgot_password

### ISSUE THREAD

**Issue by elbidone** [meumobi/infomobi#277]
```
[2017-03-30 20:40:25] sitebuilder.DEBUG: exception 'MissingControllerException' with message 'Missing Controller' in /home/meumobi/PROJECTS/meumobi.com/releases/20170106204149/sitebuilder/lib/core/controller/Controller.php:65 Stack trace: #0 /home/meumobi/PROJECTS/meumobi.com/releases/20170106204149/sitebuilder/config/initializers/dispatcher.php(356): Controller::load('ApiController', true) #1 /home/meumobi/PROJECTS/meumobi.com/releases/20170106204149/sitebuilder/lib/lithium/util/collection/Filters.php(183): {closure}('lithium\\action\\...', Array, Object(lithium\util\collection\Filters)) #2 /home/meumobi/PROJECTS/meumobi.com/releases/20170106204149/sitebuilder/lib/lithium/core/StaticObject.php(126): lithium\util\collection\Filters::run('lithium\\action\\...', Array, Array) #3 /home/meumobi/PROJECTS/meumobi.com/releases/20170106204149/sitebuilder/lib/lithium/action/Dispatcher.php(124): lithium\core\StaticObject::_filter('run', Array, Object(Closure)) #4 /home/meumobi/PROJECTS/meumobi.com/releases/20170106204149/sitebuilder/config/bootstrap.php(34): lithium\action\Dispatcher::run(Object(lithium\action\Request)) #5 /home/meumobi/PROJECTS/meumobi.com/releases/20170106204149/segments/employee/public/index.php(5): {closure}('employee') #6 {main} {"component":"general"}
```

**Comment by elbidone** [comment]
Request url should not use domain, see below url request
http://employee.meumobilesite.com/api/katrium.meumobi.com/visitors/forgot_password

**Comment by elbidone** [comment]
Due to bug on migration, only appears in dev
